Repository googleapis/nodejs-googleapis-common, pull requests merged in 2020-05, with the labels that each got.

#280 chore: unpin version of gts
  package.json
Labels: automerge, cla: yes

#277 chore: add blunderbuss config
  .github/blunderbuss.yml
Labels: automerge, cla: yes

#281 build: do not fail builds on codecov errors (#528)
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#283 feat: add stream method options interface
  src/api.ts
  src/index.ts
Labels: cla: yes
