Repository googleapis/nodejs-googleapis-common, pull requests merged in 2020-02, with the labels that each got.

#214 chore: skip img.shields.io in docs test
  linkinator.config.json
Labels: cla: yes

#213 test: modernize mocha config
  .mocharc.json
  package.json
  test/mocha.opts
Labels: cla: yes

#216 build: add GitHub actions config for unit tests
  .github/workflows/ci.yaml
  package.json
Labels: cla: yes, kokoro:force-run

#221 build: add publish.yml enabling GitHub app for publishes
  .github/publish.yml
Labels: automerge, cla: yes

#222 chore: update jsdoc.js
  .jsdoc.js
Labels: automerge, cla: yes

#223 chore: update .jsdoc.js by add protos and remove double quotes
  .jsdoc.js
Labels: automerge, cla: yes

#224 chore: correct .jsdoc.js protos and double quotes
  .jsdoc.js
Labels: automerge, cla: yes
